#!/bin/sh /etc/rc.common
# Modem LEDs on the AW1000 front panel (see /usr/sbin/aw1000-leds).

START=99
USE_PROCD=1

start_service() {
	[ "$(uci -q get aw1000_leds.main.enabled)" = 0 ] && return

	procd_open_instance
	procd_set_param command /usr/sbin/aw1000-leds
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	/usr/sbin/aw1000-leds off
}

service_triggers() {
	procd_add_reload_trigger aw1000_leds
}
